include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    omit_local_variable_types: true

analyzer:
  exclude:
    - lib/src/yaru_icons.dart
