name: yaru_icons
version: 0.1.1
homepage: https://github.com/ubuntu/yaru_icons.dart
description: Ubuntu Yaru Icon theme

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
    
flutter:
  fonts:
    - family: YaruIcons
      fonts:
        - asset: assets/ui_icons.ttf
