name: yaru_icons
version: 2.3.0
homepage: https://github.com/ubuntu/yaru_icons.dart
description: Ubuntu Yaru Icon theme

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  fonts:
    - family: YaruIcons
      fonts:
        - asset: assets/yaru_icons.otf

dev_dependencies:
  flutter_lints: ">=2.0.1 <4.0.0"

icon_font:
  input_svg_dir: "assets/icons/"
  output_font_file: "assets/yaru_icons.otf"

  output_class_file: "lib/src/yaru_icons.dart"
  symlink_map_file: "assets/symlinks.json"
  class_name: "YaruIcons"
  package: yaru_icons
  format: false
  naming_strategy: "snake"

  font_name: "YaruIcons"
  normalize: false
  ignore_shapes: false

  recursive: true
  verbose: true
