name: yaru_icons
version: 2.2.2
homepage: https://github.com/ubuntu/yaru_icons.dart
description: Ubuntu Yaru Icon theme

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.2.0"

dependencies:
  animated_vector:
    git:
      url: https://github.com/HrX03/animated_vector
      path: packages/animated_vector
  animated_vector_annotations:
    git:
      url: https://github.com/HrX03/animated_vector
      path: packages/animated_vector_annotations
  flutter:
    sdk: flutter

flutter:
  fonts:
    - family: YaruIcons
      fonts:
        - asset: assets/yaru_icons.otf

dev_dependencies:
  animated_vector_gen:
    git:
      url: https://github.com/HrX03/animated_vector
      path: packages/animated_vector_gen
  build_runner: ^2.4.6
  flutter_lints: ^2.0.1

icon_font:
  input_svg_dir: "assets/icons/"
  output_font_file: "assets/yaru_icons.otf"

  output_class_file: "lib/src/yaru_icons.dart"
  symlink_map_file: "assets/symlinks.json"
  class_name: "YaruIcons"
  package: yaru_icons
  format: false
  naming_strategy: "snake"

  font_name: "YaruIcons"
  normalize: false
  ignore_shapes: false

  recursive: true
  verbose: true
