name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: dart
          changelog-notes-type: github
          pull-request-title-pattern: 'chore: release v${version}'
